### PR TITLE
Set -Dpython.console.encoding=UTF-8 by default

### LINKED ISSUE #56: Prevent the `UnsupportedCharsetException: cp0` when using Jython script
Currently if a home made jython script/macro is saved as a plugin and executed, it runs fine but the following error message is still displayed : 

`console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.`

It can be fixed by adding the following argument to the ImageJ.cfg (after Xmx****m for instance) or to the command line (for headless mode)
`-Dpython.console.encoding=UTF-8`

It would be nice to have it as a default.

This is reported on the forum [here](https://forum.image.sc/t/script-editor-error-with-python/11438) and [there](https://forum.image.sc/t/script-editor-error-when-working-with-python-scripts/5893)

### PR DESCRIPTION
**Pull request by stelfrich**
Fixes #56.

### CODE REVIEW

**Comment by stelfrich** [comment]
@imagejan Do you have a Windows 7 machine that you could build/test this PR on? I only have a 32bit Windows 10 that I could use to compile the launcher, but not a Windows 7 one to properly test it...

**Comment by imagejan** [comment]
I wanted to take the opportunity to set up a running `gcc` on my Windows system, but when running `mvn`, I get:

<details>
<summary>these Maven log messages</summary>

```
Starting Core 9 with 1 source files...
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/config.h:34,
[ERROR]                  from c/config.c:32:
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[ERROR]  extern inline int is_digit(char c);
[ERROR]                    ^~~~~~~~
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/platform.h:36,
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/file-funcs.h:34,
[ERROR] c/ImageJ.c: In function 'adjust_java_home_if_necessary':
[ERROR]                  from c/java.c:33:
[ERROR]                  from c/platform.c:33:
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[WARNING] c/ImageJ.c:2313:20: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
[ERROR]  extern inline int is_digit(char c);
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[ERROR]                    ^~~~~~~~
[ERROR]   char* debugPath = get_library_path();
[ERROR]  extern inline int is_digit(char c);
[ERROR]                     ^~~~~~~~~~~~~~~~
[ERROR]                    ^~~~~~~~
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/config.h:34,
[ERROR]                  from c/ImageJ.c:71:
[ERROR] c/ImageJ.c: At top level:
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[ERROR]  extern inline int is_digit(char c);
[ERROR]                    ^~~~~~~~
[ERROR] c/exe-ico.c: In function 'set_exe_icon':
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/file-funcs.h:34,
[ERROR] In file included from c/file-funcs.c:33:
[ERROR]                  from c/splash.c:33:
[WARNING] c/exe-ico.c:141:7: warning: implicit declaration of function 'file_exists'; did you mean 'filelength'? [-Wimplicit-function-declaration]
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[ERROR] c/file-funcs.c: In function 'mkdir_recursively':
[ERROR]  extern inline int is_digit(char c);
[ERROR]   if (!file_exists(exe_path)) {
[ERROR]                    ^~~~~~~~
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/platform.h:114:15: warning: implicit declaration of function 'fake_posix_mkdir' [-Wimplicit-function-declaration]
[ERROR]        ^~~~~~~~~~~
[ERROR]  #define mkdir fake_posix_mkdir
[ERROR]        filelength
[ERROR]                ^~~~~~~~~~~~~~~~
[ERROR] E:\code\imagej\imagej-launcher\src\main\include/platform.h:114:15: note: in definition of macro 'mkdir'
[ERROR]  #define mkdir fake_posix_mkdir
[ERROR]                ^~~~~~~~~~~~~~~~
[ERROR] c/file-funcs.c: In function 'find_newest':
[WARNING] c/file-funcs.c:509:13: warning: implicit declaration of function 'file_is_newer' [-Wimplicit-function-declaration]
[ERROR]     else if (file_is_newer(path->buffer, result->buffer)) {
[ERROR]              ^~~~~~~~~~~~~
[ERROR] In file included from E:\code\imagej\imagej-launcher\src\main\include/file-funcs.h:34,
[ERROR]                  from c/file-funcs.c:32:
[ERROR] c/file-funcs.c: At top level:
[WARNING] E:\code\imagej\imagej-launcher\src\main\include/string-funcs.h:67:19: warning: inline function 'is_digit' declared but never defined
[ERROR]  extern inline int is_digit(char c);
[ERROR]                    ^~~~~~~~
[INFO] 10 files were compiled.
```
</details>

<br/>

and in the `target` folder, I end up with `imagej-launcher-5.0.1-SNAPSHOT-amd64-Windows-gcc-executable.nar` which apparently isn't the right thing for my platform, is it?

---

@stelfrich if you can provide me with a compiled launcher executable, I'm happy to test it on a Windows 7 system.

**Comment by ctrueden** [comment]
Maybe the easiest thing would be to merge this, wait for the AppVeyor build and use that? And then revert if there is any regression noticed?

**Comment by stelfrich** [comment]
> Maybe the easiest thing would be to merge this, wait for the AppVeyor build and use that? And then revert if there is any regression noticed?

Let's do this. Shouldn't break anything...

**Comment by imagejan** [comment]
I downloaded [`imagej-launcher-5.0.1-20180821.152133-36-win64.exe`](http://maven.imagej.net/service/local/repositories/snapshots/content/net/imagej/imagej-launcher/5.0.1-SNAPSHOT/imagej-launcher-5.0.1-20180821.152133-36-win64.exe) and put it into my existing Fiji installation on Windows 7.

This is what I noticed:

* the new launcher doesn't _seem_ to pick up my system Java: when trying to launch, it complains:
  ```
  The program can't start because jvm.dll is missing from your computer.
  ```
  But after a short while (without splash screen), the ImageJ window comes up, reporting Java 10.0.1

  (Note that the previous launcher `imagej-launcher-5.0.0-20171212.062926-36-win64.exe` in the same Fiji installation runs fine with Java 1.8.0_172 and displaying a Fiji splash screen.)

* when renaming the `java-old` directory in my installation back to `java`, both launchers start up with splash screen and Java 1.8.0_66

* when I do *File > New > Script...*, then *Language > Python*, then *Run*, I still get:
  ```
  console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.
  ```
  in all situations tested... :cry:

**Comment by imagejan** [comment]
> does not have the PR included yet (according to its timestamp at least)

sorry for that: I was getting the SNAPSHOT from maven.imagej.net, but didn't double-check the timestamp...

> Would you mind checking again with imagej-launcher-5.0.1-20180925.115628-44-win64.exe?

Yup, with this one I don't get the error message any more. I tried with Java 10.0.1 (after that spurious jvm.dll error dialog mentioned above) and with the bundled Java 1.8.0_66, it's fine in both cases.

Thanks again, @stelfrich!

**Comment by ctrueden** [comment]
Did anyone try setting this flag on the _Java side_ using `System.setProperty` instead of in the native code?

**Pull request merged**
