### PR TITLE
Revise launcher discovery

### LINKED ISSUE #69: JRE not detected on linux64
The laucher is not able to pick up the JRE shipped with the latest Fiji version, see [this issue](https://github.com/fiji/fiji/issues/258). 

To get the most recent launcher version, we used the `trim-the-fat` branch (which should probably be finished and merged, as far as I understood?) and deleted [this commit](https://github.com/imagej/imagej-launcher/commit/5702c02c07792983ad433f7e66b321e9b7a5c650), otherwise it would not build. The resulting Imagej-linux64 binary prints this message: 
```
Could not load Java library '/media/data/Programs/Fiji.app/java/linux-amd64/jdk1.8.0_172/jre//lib/server/libjvm.so': /media/data/Programs/Fiji.app/java/linux-amd64/jdk1.8.0_172/jre//lib/server/libjvm.so: cannot open shared object file: No such file or directory
Warning: falling back to System JVM
```
It tries to use `lib/server/libjvm.so` instead of `lib/amd64/server/libjvm.so` which would be the correct path.

I think I was able to track it down to [this line](https://github.com/imagej/imagej-launcher/blob/1049eac6ec9931b1e98bcecc078865a5bca78afd/src/main/c/java.c#L431) where it should pick `lib/amd64/server/libjvm.so` but used `lib/server/libjvm.so` instead.

### PR DESCRIPTION
**Pull request by hinerm**
Removes the `guess_java_version` logic in favor of requiring a platform-specific `/java/` subdirectory for detecting bundled javas.

The corresponding changes to logic in what was `adjust_java_home_if_necessary` should allow us to support any Java vendor on mac, linux and windows.

Closes #69 and https://github.com/fiji/fiji/issues/258

### CODE REVIEW

**Comment by hinerm** [comment]
@ctrueden can you test the `run-java-gauntlet` on OSX? It works for me on Windows and Linux.

**Comment by ctrueden** [comment]
I did some light cleanup of commit message, and force pushed. All commits compile with passing tests. ✅ 

However, the launcher does not work on macOS anymore:
```
$ Contents/MacOS/ImageJ-macosx
Error occurred during initialization of VM
Unable to load native library: dlopen(/Users/curtis/Applications/Fiji.app/java/macosx/adoptopenjdk-8.jdk/jre/Contents/Home/lib/libjava.dylib, 1): image not found
```

I'll investigate and commit a fix, probably tomorrow.

Note that on macOS, we need to link to `libjli.dylib`, _not_ `libjvm.dylib`. Sorry I forgot about that. I have no idea where `libjava.dylib` is coming from—will investigate once I have dealt with some more urgent priorities today.

**Comment by ctrueden** [comment]
@hinerm I fixed the logic for macOS (and maybe other platforms). Aside from a lot of refactoring and debugging improvements, a9a85723436e85cfd8cce03cb68be75c0a02903c is what was needed. I.e.: search for `libjli.dylib` even when we have a java home that _isn't_ a bundled java. Previously, the smart searching was limited to digging through only the bundled java directories, AFAICT.

There is still weirdness. Here's the end of a successful run on my system:
```
        find_newest complete with result: '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'
        set_relative_java_home:
            relative_java_home -> dk-8.jdk/Contents/Home/
        set_library_path:
            library_path is now jre/lib/jli/libjli.dylib
        Default library path (relative): jre/lib/jli/libjli.dylib
Opening Java library /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib
get_jre_home:
    get_jre_home: Returning /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
java.vendor = AdoptOpenJDK
java.version = 1.8.0_265
```
See the `relative_java_home`? Definitely wrong. What is that even for? Clearly it's not being used here. Is it ever needed? Should we get rid of it? [YOU DECIDE!](https://www.youtube.com/user/ERB) 🤣

**Comment by hinerm** [comment]
Closed in favor of https://github.com/imagej/imagej-launcher/pull/74

**Pull request closed without merging**
